version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - cicd-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cicd-network

networks:
  cicd-network:
    driver: bridge

volumes:
  node_modules: 